image: hatsoftwares/lstu-test-ci:latest
stages:
  - publish_changelog
  - pouet_it
  - carton
  - carton_bdd
  - tests
variables:
  POSTGRES_DB: lstu_db
  POSTGRES_USER: lstu
  POSTGRES_PASSWORD: lstu_pwd
  MYSQL_DATABASE: lstu_db
  MYSQL_USER: lstu
  MYSQL_PASSWORD: lstu_pwd
  MYSQL_ROOT_PASSWORD: root

before_script:
  - if [[ $CI_JOB_NAME == "postgresql 3/3" ]]; then export PGPASSWORD=lstu_pwd; echo 'CREATE DATABASE lstu_minion WITH OWNER lstu;' | psql -h postgres -U lstu lstu_db; fi
  - if [[ $CI_JOB_NAME == "mysql 3/3" ]]; then echo "CREATE DATABASE lstu_minion; GRANT ALL ON lstu_minion.* TO lstu@'%'; FLUSH PRIVILEGES;" | mysql -h mariadb -u root -proot; fi
  - which mariadb_config && cd $(dirname $(which mariadb_config)) && ln -s mariadb_config mysql_config && cd -

### Jobs templates
##
#
.retry: &retry
  retry: 2
  except:
    - tags
.carton_bdd_template: &carton_bdd_definition
  <<: *retry
  stage: carton_bdd
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - local/
    policy: pull
  needs:
    - carton
  artifacts:
    paths:
      - local.tar
    expire_in: 3 hours
  after_script:
    - tar cf local.tar local/

.tests_template: &tests_definition
  <<: *retry
  stage: tests
  parallel: 3
  script:
    - tar xf local.tar && rm local.tar
    - export CI_JOB_NAME=$(echo $CI_JOB_NAME | sed -e 's@ .*@@')
    - echo "Database $CI_JOB_NAME test $CI_NODE_INDEX on $CI_NODE_TOTAL"
    - if [[ $CI_NODE_INDEX -eq 3 ]]; then MOJO_CONFIG="t/${CI_JOB_NAME}${CI_NODE_INDEX}.conf" make minion & sleep 5; fi
    - MOJO_CONFIG="t/${CI_JOB_NAME}${CI_NODE_INDEX}.conf" make test
    - MOJO_CONFIG="t/${CI_JOB_NAME}${CI_NODE_INDEX}.conf" make cover
  coverage: '/Total.* (\d+\.\d+)$/'

.sqlite_template: &sqlite_definition
  <<: *tests_definition
  dependencies:
    - carton_sqlite
  needs:
    - carton_sqlite
  services:
    - name: rroemhild/test-openldap
      alias: rroemhild-test-openldap

.pg_template: &pg_definition
  <<: *tests_definition
  dependencies:
    - carton_postgresql
  needs:
    - carton_postgresql
  services:
    - name: rroemhild/test-openldap
      alias: rroemhild-test-openldap
    - name: postgres:9.6
      alias: postgres

.mysql_template: &mysql_definition
  <<: *tests_definition
  dependencies:
    - carton_mysql
  needs:
    - carton_mysql
  services:
    - name: rroemhild/test-openldap
      alias: rroemhild-test-openldap
    - name: mariadb:10.1
      alias: mariadb

### Publish tag changelog and create a toot
##
#
include:
  - 'https://framagit.org/fiat-tux/gitlabci-snippets/raw/4e4e03322e95e9b0124c714456ebf1bdc02ad43f/publish_changelog.gitlab-ci.yml'
  - 'https://framagit.org/fiat-tux/gitlabci-snippets/raw/4e4e03322e95e9b0124c714456ebf1bdc02ad43f/pouet-it-from-ci.gitlab-ci.yml'

### Podcheck
##
#
podcheck:
  <<: *retry
  stage: carton
  script:
    - make podcheck

### Install common dependencies
##
#
carton:
  <<: *retry
  stage: carton
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - local/
  script:
    - carton install --deployment --without=sqlite --without=postgresql --without=mysql

### Install DB related dependencies
##
#
carton_sqlite:
  <<: *carton_bdd_definition
  script:
    - carton install --deployment --without=postgresql --without=mysql
carton_postgresql:
  <<: *carton_bdd_definition
  script:
    - carton install --deployment --without=sqlite --without=mysql
carton_mysql:
  <<: *carton_bdd_definition
  script:
    - carton install --deployment --without=sqlite --without=postgresql

### Tests
##
#
sqlite:
  <<: *sqlite_definition
postgresql:
  <<: *pg_definition
mysql:
  <<: *mysql_definition
